# Generated by Django 5.2.4 on 2025-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj_basico', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('natureza_juridica', models.CharField(blank=True, max_length=4, null=True)),
                ('qualificacao_responsavel', models.CharField(blank=True, max_length=2, null=True)),
                ('capital_social', models.CharField(blank=True, max_length=20, null=True)),
                ('porte_empresa', models.CharField(blank=True, max_length=2, null=True)),
                ('ente_federativo_responsavel', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
